---
functional:
  - пользователь должен иметь возможность авторизации через Github и Discord
  - пользователь должен иметь возможность сыграть без авторизации
  - возможность задать параметры игры, а именно сложность, выбор оппонента, лимит времени, тип задания
  - функции сдаться, сброса кода, проверки решения в терминале
  - возможность задать параметры в процессе игры, а именно язык программирования, язык  вывода заданий на экран, использовать редактор Vim и переключать темную и светлую тему в терминале
  - возможность просмотра истории баттлов и лидербордов
  - возможность просмотра повтора баттла
  - возможность просмотра баттла зрителям в режиме online
  - возможность организации турниров и турнирной сетки
  - возможность переподключения участника к баттлу
  - после определения победителя должна быть возможность остаться в баттле и дописать код или ознакомиться с кодом
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - пользователь может вносить изменения только в своем терминале
  - третьи лица не могут вносить изменения в код, задачу или иные поля в интерфейсе
  - узнаваемые элементы веб-дизайна - фирменные цвета, логотип, иконка, шрифты
  - возможность писать сообщения в чат
  - возможность просмотра игроков online
  - возможность просмотра профиля игрока
  - возможность пригласить игрока в игру
